language: python
before_install:
  - sudo apt-get -y install libsuitesparse-dev cmake libeigen3-dev  libqglviewer-dev
  - ./setup.sh
addons:
  apt:
    update: true
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
